// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(EntityFrameworkContext))]
    [Migration("20210608100123_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesCourse_id")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudent_id")
                        .HasColumnType("int");

                    b.HasKey("CoursesCourse_id", "StudentsStudent_id");

                    b.HasIndex("StudentsStudent_id");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("EntityFramework.Models.Assignment", b =>
                {
                    b.Property<int>("Assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<int?>("Course_id1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Assignment_id");

                    b.HasIndex("Course_id1");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EntityFramework.Models.Course", b =>
                {
                    b.Property<int>("Course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Teacher_id")
                        .HasColumnType("int");

                    b.Property<int?>("Teacher_id1")
                        .HasColumnType("int");

                    b.HasKey("Course_id");

                    b.HasIndex("Teacher_id1");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EntityFramework.Models.Student", b =>
                {
                    b.Property<int>("Student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Student_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EntityFramework.Models.Teacher", b =>
                {
                    b.Property<int>("Teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("EntityFramework.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFramework.Models.Assignment", b =>
                {
                    b.HasOne("EntityFramework.Models.Course", null)
                        .WithMany("Assignments")
                        .HasForeignKey("Course_id1");
                });

            modelBuilder.Entity("EntityFramework.Models.Course", b =>
                {
                    b.HasOne("EntityFramework.Models.Teacher", null)
                        .WithMany("Courses")
                        .HasForeignKey("Teacher_id1");
                });

            modelBuilder.Entity("EntityFramework.Models.Course", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("EntityFramework.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
